name: MLflow Retrain on Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: recruitment_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Train Model with MLflow
        working-directory: MLProject
        run: |
          mlflow run . --entry-point main

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained_model
          path: ./MLProject/mlruns/
